runtime: php72



env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:HOp/38aL8FpTwQtb7BnCXY5tQGuCfYbYma5m7JHW9mE=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie


